version: '3.8'

services:
  postgres:
    build: ./postgres
    container_name: solana_trading_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-trading_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-trading_password}
      POSTGRES_DB: ${POSTGRES_DB:-trading_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-trading_user} -d ${POSTGRES_DB:-trading_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trading_network

networks:
  trading_network:
    driver: bridge